# Generated by Django 5.1.3 on 2024-11-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_studentsubjectenrollment_delete_studentsubject'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
